### ISSUE TITLE
Provide documentation on creating and using slides

### ISSUE THREAD

**Issue by lyashevska** [esciencecenter-digital-skills/good-practices-in-research-software-development#21]
Documentation is needed on how to create (@OleMussmann  we need your help on this one), update and run slides. 

This relates to #18

**Comment by OleMussmann** [comment]
Manual for creating, serving, publishing and using the theme elements is here: https://nlesc-slides.github.io/2024-06-03_slide_manual/

I did not attempt to replicate the core features of reveal.js (yet?), because it is a rather bottomless pit end the official documentation at https://revealjs.com/ is really good.

Please re-open this issue if you need more details, or other changes to the manual.

**Comment by lyashevska** [comment]
Great manual, Ole! Thanks! we need to link it somewhere so people can find it. Perhaps a readme? Also since tempate has changed, how can we 'migrate' [this](https://lyashevska.github.io/ds-cr-slides/) slides?
